package monopoly.decks;

public enum ChanceCard {
    ADVANCE_TO_BOARDWALK,
    ADVANCE_TO_GO,
    ADVANCE_TO_ILLINOIS_AVENUE,
    ADVANCE_TO_ST_CHARLES_PLACE,
    ADVANCE_TO_NEAREST_RAILROAD_0,
    ADVANCE_TO_NEAREST_RAILROAD_1,
    ADVANCE_TO_NEAREST_UTILITY,
    BANK_PAYS_YOU,
    GET_OUT_OF_JAIL_FREE,
    GO_BACK_THREE_SPACES,
    GO_TO_JAIL,
    MAKE_GENERAL_REPAIRS,
    SPEEDING_FINE,
    TRIP_TO_READING_RAILROAD,
    ELECTED_CHAIRMAN,
    BUILDING_LOAN
}
